### ISSUE TITLE
Issue on Windows

### ISSUE THREAD

**Issue by mattalhonte** [andrewvida/isomorphic-clojurescript-reagent-node#3]
Awesome post!  

Just had one issue.  It worked fine under Ubuntu, but when I tried it under Windows 10 I got this error (even git cloned this repository to make sure I didn't mistype any code): 

`Error: ENOENT: no such file or directory, open 'C:\Users\Matt\Desktop\ClojureWorkspace\ClojureScript\isomorphic-clojurescript-reageneact.inc.js'rcespublicjsserver-side
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.nodeGlobalRequire (C:\Users\Matt\Desktop\ClojureWorkspace\ClojureScript\isomorphic-clojurescript-reagent-node\resources\public\js\server-side\goog\bootstrap\nodejs.js:85:26)
    at Object.cljs$core$load_file [as load_file] (C:\Users\Matt\Desktop\ClojureWorkspace\ClojureScript\isomorphic-clojurescript-reagent-node\resources\public\js\server-side\cljs\core.cljs:273:5)
    at Object.<anonymous> (C:\Users\Matt\Desktop\ClojureWorkspace\ClojureScript\isomorphic-clojurescript-reagent-node\resources\public\js\server-side\reagent\impl\util.cljs:1:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)`

From the looks of it, seems like it's not processing Window slashes correctly.  This may be an issue with Node, though, I guess?

**Comment by andrewvida** [comment]
I'm glad you enjoyed it @mattalhonte!  I don't have access to a Windows machine at the moment, but chances are you're correct about the slashes.  I'd have to dig into it more to determine. 

Thanks for bringing it to my attention.
